name: The website deployment to the cpanel

run-name: Deploying the website to the cpanel

on:
  push:
   branches: [ "main" ]

jobs:
    FTP-Deploy-Action:
     name: 🎉 Deploy
     runs-on: ubuntu-latest

     steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: 🔨 Build Project
        run: |
         npm install
         npm run build

      - name: 📂 Sync folders and files to the server
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: dist/